#include "tfs_key_manager.h"
#include "item.h"
#include "items.h"
#include "action.h"

#include <wx/msgdlg.h>
#include <wx/panel.h>
#include <sstream>

BEGIN_EVENT_TABLE(TFSKeyDoorDialog, wxDialog)
EVT_BUTTON(wxID_OK, TFSKeyDoorDialog::OnClickApply)
EVT_BUTTON(wxID_CANCEL, TFSKeyDoorDialog::OnClickCancel)
END_EVENT_TABLE()

TFSKeyDoorDialog::TFSKeyDoorDialog(wxWindow* parent, Editor& editor, Tile* target_tile) :
	wxDialog(parent, wxID_ANY, "TFS 1.6 Key & Door Manager", wxDefaultPosition, wxSize(440, 380), wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
	editor(editor),
	tile(target_tile),
	assigned_key_aid(3001) {

	SetBackgroundColour(wxColour(10, 20, 35));
	wxBoxSizer* topsizer = newd wxBoxSizer(wxVERTICAL);

	// Header Banner Panel
	wxPanel* headerPanel = newd wxPanel(this, wxID_ANY);
	headerPanel->SetBackgroundColour(wxColour(16, 28, 48));
	wxBoxSizer* headerSizer = newd wxBoxSizer(wxVERTICAL);

	wxStaticText* header = newd wxStaticText(headerPanel, wxID_ANY, "Pair Key & Locked Door (TFS 1.6)");
	header->SetFont(wxFont(13, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD));
	header->SetForegroundColour(wxColour(180, 150, 50));

	wxStaticText* subheader = newd wxStaticText(headerPanel, wxID_ANY, "Binds key items (2088-2092) to locked doors via matching ActionIDs.");
	subheader->SetFont(wxFont(9, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL));
	subheader->SetForegroundColour(wxColour(180, 190, 205));

	headerSizer->Add(header, 0, wxBOTTOM, 4);
	headerSizer->Add(subheader, 0);
	headerPanel->SetSizer(headerSizer);

	topsizer->Add(headerPanel, 0, wxEXPAND | wxALL, 12);

	// Card Container
	wxPanel* cardPanel = newd wxPanel(this, wxID_ANY);
	cardPanel->SetBackgroundColour(wxColour(16, 28, 48));
	wxBoxSizer* cardSizer = newd wxBoxSizer(wxVERTICAL);

	wxFlexGridSizer* grid = newd wxFlexGridSizer(2, 8, 12);
	grid->AddGrowableCol(1);

	auto addLabel = [cardPanel, grid](const wxString& labelText) {
		wxStaticText* label = newd wxStaticText(cardPanel, wxID_ANY, labelText);
		label->SetForegroundColour(wxColour(180, 190, 205));
		label->SetFont(wxFont(9, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD));
		grid->Add(label, 0, wxALIGN_CENTER_VERTICAL);
	};

	auto styleTextCtrl = [](wxTextCtrl* ctrl) {
		ctrl->SetBackgroundColour(wxColour(16, 28, 48));
		ctrl->SetForegroundColour(wxColour(240, 245, 255));
	};

	auto styleSpinCtrl = [](wxSpinCtrl* ctrl) {
		ctrl->SetBackgroundColour(wxColour(16, 28, 48));
		ctrl->SetForegroundColour(wxColour(240, 245, 255));
	};

	addLabel("Key Item ID:");
	keyItemIdSpin = newd wxSpinCtrl(cardPanel, wxID_ANY, "2088", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 2088, 2092, 2088);
	styleSpinCtrl(keyItemIdSpin);
	grid->Add(keyItemIdSpin, 1, wxEXPAND);

	addLabel("Key Action ID (aid):");
	keyActionIdSpin = newd wxSpinCtrl(cardPanel, wxID_ANY, "3001", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 100, 65535, 3001);
	styleSpinCtrl(keyActionIdSpin);
	grid->Add(keyActionIdSpin, 1, wxEXPAND);

	addLabel("Key Label / Name:");
	keyNameCtrl = newd wxTextCtrl(cardPanel, wxID_ANY, "Copper Key (3001)");
	styleTextCtrl(keyNameCtrl);
	grid->Add(keyNameCtrl, 1, wxEXPAND);

	cardSizer->Add(grid, 1, wxEXPAND | wxALL, 12);
	cardPanel->SetSizer(cardSizer);

	topsizer->Add(cardPanel, 1, wxEXPAND | wxLEFT | wxRIGHT | wxBOTTOM, 12);

	// Action Buttons
	wxBoxSizer* btnsizer = newd wxBoxSizer(wxHORIZONTAL);
	wxButton* okBtn = newd wxButton(this, wxID_OK, "Apply to Door");
	wxButton* cancelBtn = newd wxButton(this, wxID_CANCEL, "Cancel");

	okBtn->SetBackgroundColour(wxColour(35, 75, 150));
	okBtn->SetForegroundColour(wxColour(240, 210, 120));
	okBtn->SetFont(wxFont(9, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD));

	cancelBtn->SetBackgroundColour(wxColour(22, 36, 58));
	cancelBtn->SetForegroundColour(wxColour(180, 190, 205));

	btnsizer->Add(okBtn, 0, wxRIGHT, 8);
	btnsizer->Add(cancelBtn, 0);

	topsizer->Add(btnsizer, 0, wxALIGN_RIGHT | wxLEFT | wxRIGHT | wxBOTTOM, 12);
	SetSizerAndFit(topsizer);

	if (tile) {
		Item* top_item = tile->getTopItem();
		if (top_item && top_item->getActionID() != 0) {
			keyActionIdSpin->SetValue(top_item->getActionID());
		}
	}
}

TFSKeyDoorDialog::~TFSKeyDoorDialog() {
}

void TFSKeyDoorDialog::OnClickApply(wxCommandEvent& WXUNUSED(event)) {
	int key_id = keyItemIdSpin->GetValue();
	int key_aid = keyActionIdSpin->GetValue();
	std::string key_name = nstr(keyNameCtrl->GetValue());

	assigned_key_aid = static_cast<uint32_t>(key_aid);

	std::ostringstream ss;
	ss << "-- Generated by Mios Map Editor for TFS 1.6 RevScriptSys\n";
	ss << "-- Key & Door Binding for Key ID " << key_id << " and ActionID " << key_aid << "\n";
	ss << "local keyDoor = Action()\n\n";
	ss << "function keyDoor.onUse(player, item, fromPosition, target, toPosition, isHotkey)\n";
	ss << "\tif target and target.actionid == " << key_aid << " then\n";
	ss << "\t\tplayer:sendTextMessage(MESSAGE_EVENT_ADVANCE, \"You unlock the door.\")\n";
	ss << "\t\treturn true\n";
	ss << "\tend\n";
	ss << "\treturn false\n";
	ss << "end\n\n";
	ss << "keyDoor:id(" << key_id << ")\n";
	ss << "keyDoor:register()\n";

	generated_script = ss.str();

	if (tile) {
		Item* top_item = tile->getTopItem();
		if (top_item) {
			Tile* new_tile = tile->deepCopy(editor.map);
			Item* new_top = new_tile->getTopItem();
			if (new_top) {
				new_top->setActionID(assigned_key_aid);
				if (!key_name.empty()) {
					new_top->setAttribute("name", key_name);
				}
			}
			Action* action = editor.actionQueue->createAction(ACTION_CHANGE_PROPERTIES);
			action->addChange(newd Change(new_tile));
			editor.addAction(action);
		}
	}

	EndModal(wxID_OK);
}

void TFSKeyDoorDialog::OnClickCancel(wxCommandEvent& WXUNUSED(event)) {
	EndModal(wxID_CANCEL);
}
