#include "tfs_quest_generator.h"
#include "item.h"
#include "items.h"
#include "action.h"
#include "gui.h"

#include <wx/msgdlg.h>
#include <sstream>

BEGIN_EVENT_TABLE(TFSQuestDialog, wxDialog)
EVT_BUTTON(wxID_OK, TFSQuestDialog::OnClickGenerate)
EVT_BUTTON(wxID_CANCEL, TFSQuestDialog::OnClickCancel)
END_EVENT_TABLE()

TFSQuestDialog::TFSQuestDialog(wxWindow* parent, Editor& editor, Tile* target_tile) :
	wxDialog(parent, wxID_ANY, "TFS 1.6 Quest Chest Creator", wxDefaultPosition, wxSize(450, 480), wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
	editor(editor),
	tile(target_tile),
	assigned_aid(2000) {

	SetBackgroundColour(wxColour(15, 23, 42));
	wxBoxSizer* topsizer = newd wxBoxSizer(wxVERTICAL);

	wxStaticText* header = newd wxStaticText(this, wxID_ANY, "Create TFS 1.6 Quest Chest Script");
	header->SetFont(wxFont(12, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD));
	header->SetForegroundColour(wxColour(241, 245, 249));
	topsizer->Add(header, 0, wxALL, 12);

	wxFlexGridSizer* grid = newd wxFlexGridSizer(2, 8, 12);
	grid->AddGrowableCol(1);

	auto addLabel = [this, grid](const wxString& labelText) {
		wxStaticText* label = newd wxStaticText(this, wxID_ANY, labelText);
		label->SetForegroundColour(wxColour(203, 213, 225));
		grid->Add(label, 0, wxALIGN_CENTER_VERTICAL);
	};

	addLabel("Quest Name:");
	questNameCtrl = newd wxTextCtrl(this, wxID_ANY, "MyFirstQuest");
	grid->Add(questNameCtrl, 1, wxEXPAND);

	addLabel("Storage Value ID:");
	storageIdSpin = newd wxSpinCtrl(this, wxID_ANY, "50001", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 1, 999999, 50001);
	grid->Add(storageIdSpin, 1, wxEXPAND);

	addLabel("Action ID (aid):");
	actionIdSpin = newd wxSpinCtrl(this, wxID_ANY, "2001", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 100, 65535, 2001);
	grid->Add(actionIdSpin, 1, wxEXPAND);

	addLabel("Reward Item ID:");
	rewardItemIdSpin = newd wxSpinCtrl(this, wxID_ANY, "2160", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 1, 40000, 2160);
	grid->Add(rewardItemIdSpin, 1, wxEXPAND);

	addLabel("Reward Item Count:");
	rewardCountSpin = newd wxSpinCtrl(this, wxID_ANY, "10", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 1, 100, 10);
	grid->Add(rewardCountSpin, 1, wxEXPAND);

	addLabel("Reward Experience:");
	rewardExpSpin = newd wxSpinCtrl(this, wxID_ANY, "1000", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 10000000, 1000);
	grid->Add(rewardExpSpin, 1, wxEXPAND);

	addLabel("Success Message:");
	successMsgCtrl = newd wxTextCtrl(this, wxID_ANY, "You have found 10 crystal coins.");
	grid->Add(successMsgCtrl, 1, wxEXPAND);

	addLabel("Empty Message:");
	emptyMsgCtrl = newd wxTextCtrl(this, wxID_ANY, "It is empty.");
	grid->Add(emptyMsgCtrl, 1, wxEXPAND);

	topsizer->Add(grid, 1, wxEXPAND | wxALL, 12);

	wxBoxSizer* btnsizer = newd wxBoxSizer(wxHORIZONTAL);
	wxButton* okBtn = newd wxButton(this, wxID_OK, "Generate Script");
	wxButton* cancelBtn = newd wxButton(this, wxID_CANCEL, "Cancel");
	btnsizer->Add(okBtn, 0, wxRIGHT, 8);
	btnsizer->Add(cancelBtn, 0);

	topsizer->Add(btnsizer, 0, wxALIGN_RIGHT | wxALL, 12);
	SetSizerAndFit(topsizer);

	if (tile) {
		Item* top_item = tile->getTopItem();
		if (top_item && top_item->getActionID() != 0) {
			actionIdSpin->SetValue(top_item->getActionID());
		}
	}
}

TFSQuestDialog::~TFSQuestDialog() {
}

void TFSQuestDialog::OnClickGenerate(wxCommandEvent& WXUNUSED(event)) {
	quest_name = nstr(questNameCtrl->GetValue());
	if (quest_name.empty()) {
		wxMessageBox("Please enter a valid quest name.", "Error", wxOK | wxICON_ERROR, this);
		return;
	}

	int storage_id = storageIdSpin->GetValue();
	int action_id = actionIdSpin->GetValue();
	int reward_item_id = rewardItemIdSpin->GetValue();
	int reward_count = rewardCountSpin->GetValue();
	int reward_exp = rewardExpSpin->GetValue();
	std::string success_msg = nstr(successMsgCtrl->GetValue());
	std::string empty_msg = nstr(emptyMsgCtrl->GetValue());

	assigned_aid = static_cast<uint32_t>(action_id);

	std::ostringstream ss;
	ss << "-- Generated by Mios Map Editor for TFS 1.6 RevScriptSys\n";
	ss << "local questChest = Action()\n\n";
	ss << "function questChest.onUse(player, item, fromPosition, target, toPosition, isHotkey)\n";
	ss << "\tif player:getStorageValue(" << storage_id << ") > 0 then\n";
	ss << "\t\tplayer:sendTextMessage(MESSAGE_EVENT_ADVANCE, \"" << empty_msg << "\")\n";
	ss << "\t\treturn true\n";
	ss << "\tend\n\n";
	ss << "\tplayer:setStorageValue(" << storage_id << ", 1)\n";
	if (reward_item_id > 0 && reward_count > 0) {
		ss << "\tplayer:addItem(" << reward_item_id << ", " << reward_count << ")\n";
	}
	if (reward_exp > 0) {
		ss << "\tplayer:addExperience(" << reward_exp << ", true)\n";
	}
	ss << "\tplayer:sendTextMessage(MESSAGE_EVENT_ADVANCE, \"" << success_msg << "\")\n";
	ss << "\treturn true\n";
	ss << "end\n\n";
	ss << "questChest:aid(" << action_id << ")\n";
	ss << "questChest:register()\n";

	generated_script = ss.str();

	// If a tile is selected, update its top item actionID on the map
	if (tile) {
		Item* top_item = tile->getTopItem();
		if (top_item) {
			Tile* new_tile = tile->deepCopy(editor.map);
			Item* new_top = new_tile->getTopItem();
			if (new_top) {
				new_top->setActionID(assigned_aid);
			}
			Action* action = editor.actionQueue->createAction(ACTION_CHANGE_PROPERTIES);
			action->addChange(newd Change(new_tile));
			editor.addAction(action);
		}
	}

	EndModal(wxID_OK);
}

void TFSQuestDialog::OnClickCancel(wxCommandEvent& WXUNUSED(event)) {
	EndModal(wxID_CANCEL);
}
