#include "tfs_key_manager.h"
#include "item.h"
#include "items.h"
#include "action.h"

#include <wx/msgdlg.h>
#include <sstream>

BEGIN_EVENT_TABLE(TFSKeyDoorDialog, wxDialog)
EVT_BUTTON(wxID_OK, TFSKeyDoorDialog::OnClickApply)
EVT_BUTTON(wxID_CANCEL, TFSKeyDoorDialog::OnClickCancel)
END_EVENT_TABLE()

TFSKeyDoorDialog::TFSKeyDoorDialog(wxWindow* parent, Editor& editor, Tile* target_tile) :
	wxDialog(parent, wxID_ANY, "TFS 1.6 Key & Door Manager", wxDefaultPosition, wxSize(420, 320), wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
	editor(editor),
	tile(target_tile),
	assigned_key_aid(3001) {

	SetBackgroundColour(wxColour(15, 23, 42));
	wxBoxSizer* topsizer = newd wxBoxSizer(wxVERTICAL);

	wxStaticText* header = newd wxStaticText(this, wxID_ANY, "Pair Key & Locked Door (TFS 1.6)");
	header->SetFont(wxFont(12, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD));
	header->SetForegroundColour(wxColour(241, 245, 249));
	topsizer->Add(header, 0, wxALL, 12);

	wxFlexGridSizer* grid = newd wxFlexGridSizer(2, 8, 12);
	grid->AddGrowableCol(1);

	auto addLabel = [this, grid](const wxString& labelText) {
		wxStaticText* label = newd wxStaticText(this, wxID_ANY, labelText);
		label->SetForegroundColour(wxColour(203, 213, 225));
		grid->Add(label, 0, wxALIGN_CENTER_VERTICAL);
	};

	addLabel("Key Item ID:");
	keyItemIdSpin = newd wxSpinCtrl(this, wxID_ANY, "2088", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 2088, 2092, 2088);
	grid->Add(keyItemIdSpin, 1, wxEXPAND);

	addLabel("Key Action ID (aid):");
	keyActionIdSpin = newd wxSpinCtrl(this, wxID_ANY, "3001", wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 100, 65535, 3001);
	grid->Add(keyActionIdSpin, 1, wxEXPAND);

	addLabel("Key Label / Name:");
	keyNameCtrl = newd wxTextCtrl(this, wxID_ANY, "Copper Key (3001)");
	grid->Add(keyNameCtrl, 1, wxEXPAND);

	topsizer->Add(grid, 1, wxEXPAND | wxALL, 12);

	wxBoxSizer* btnsizer = newd wxBoxSizer(wxHORIZONTAL);
	wxButton* okBtn = newd wxButton(this, wxID_OK, "Apply to Door");
	wxButton* cancelBtn = newd wxButton(this, wxID_CANCEL, "Cancel");
	btnsizer->Add(okBtn, 0, wxRIGHT, 8);
	btnsizer->Add(cancelBtn, 0);

	topsizer->Add(btnsizer, 0, wxALIGN_RIGHT | wxALL, 12);
	SetSizerAndFit(topsizer);

	if (tile) {
		Item* top_item = tile->getTopItem();
		if (top_item && top_item->getActionID() != 0) {
			keyActionIdSpin->SetValue(top_item->getActionID());
		}
	}
}

TFSKeyDoorDialog::~TFSKeyDoorDialog() {
}

void TFSKeyDoorDialog::OnClickApply(wxCommandEvent& WXUNUSED(event)) {
	int key_id = keyItemIdSpin->GetValue();
	int key_aid = keyActionIdSpin->GetValue();
	std::string key_name = nstr(keyNameCtrl->GetValue());

	assigned_key_aid = static_cast<uint32_t>(key_aid);

	std::ostringstream ss;
	ss << "-- Generated by Mios Map Editor for TFS 1.6 RevScriptSys\n";
	ss << "-- Key & Door Binding for Key ID " << key_id << " and ActionID " << key_aid << "\n";
	ss << "local keyDoor = Action()\n\n";
	ss << "function keyDoor.onUse(player, item, fromPosition, target, toPosition, isHotkey)\n";
	ss << "\tif target and target.actionid == " << key_aid << " then\n";
	ss << "\t\tplayer:sendTextMessage(MESSAGE_EVENT_ADVANCE, \"You unlock the door.\")\n";
	ss << "\t\treturn true\n";
	ss << "\tend\n";
	ss << "\treturn false\n";
	ss << "end\n\n";
	ss << "keyDoor:id(" << key_id << ")\n";
	ss << "keyDoor:register()\n";

	generated_script = ss.str();

	// If a door tile is selected, apply actionID to the door item
	if (tile) {
		Item* top_item = tile->getTopItem();
		if (top_item) {
			Tile* new_tile = tile->deepCopy(editor.map);
			Item* new_top = new_tile->getTopItem();
			if (new_top) {
				new_top->setActionID(assigned_key_aid);
				if (!key_name.empty()) {
					new_top->setAttribute("name", key_name);
				}
			}
			Action* action = editor.actionQueue->createAction(ACTION_CHANGE_PROPERTIES);
			action->addChange(newd Change(new_tile));
			editor.addAction(action);
		}
	}

	EndModal(wxID_OK);
}

void TFSKeyDoorDialog::OnClickCancel(wxCommandEvent& WXUNUSED(event)) {
	EndModal(wxID_CANCEL);
}
